/* Content lifted verbatim-in-spirit from the 2026 résumés (BE + FS variants). */
window.PORTFOLIO = {
  name: "Nicolás Mateo",
  fullName: "Nicolás Mateo Hernández Rojas",
  location: "Bogotá, Colombia",
  email: "nm.hernandez1996@gmail.com",
  site: "nicolasmateo.dev",
  github: "github.com/nmhernandez10",
  linkedin: "linkedin.com/in/nicohero",
  lenses: {
    be: {
      label: "Backend",
      role: "Senior Backend Engineer & Feature Architect",
      hero: ["Backend systems,", "owned end to end."],
      lede: "I lead technical design and delivery for a regulated mental-health platform — service and API design, relational data modeling, and event-driven architecture, with correctness and observability built in rather than added later.",
      workTitle: "Services and pipelines I own",
      skills: [
        { title: "Backend", icon: "nestjs", items: ["TypeScript", "Node.js", "NestJS", "Fastify", "Python", "REST API design", "GraphQL", "Webhooks", "Event-driven architecture"] },
        { title: "Data", icon: "postgresql", items: ["PostgreSQL", "Relational modeling", "Migrations", "Query optimization", "MongoDB", "Redis", "ETL pipelines"] },
        { title: "Cloud & DevOps", icon: "docker", items: ["AWS Lambda", "SQS", "S3", "RDS", "API Gateway", "Fargate", "Docker", "CI/CD"] },
        { title: "Observability", icon: "elasticsearch", items: ["Elasticsearch", "Kibana", "Structured logging", "Metrics", "Dashboards", "Alerting"] },
        { title: "AI engineering", icon: "claude", items: ["Claude Code", "Codex CLI", "Agentic workflows", "AWS Bedrock", "AgentCore", "Context management"] },
        { title: "Practices", icon: "git-branch", iconSet: "ui", items: ["System design", "Automated testing", "Code review", "Documentation", "Mentoring", "Feature ownership"] },
      ],
    },
    fs: {
      label: "Full stack",
      role: "Senior Full Stack Engineer & Feature Architect",
      hero: ["Schema to shipped UI,", "one pair of hands."],
      lede: "I lead technical design and delivery for a regulated mental-health platform and move between the data model and the interface without friction — service and API design, relational data modeling, design systems and shared component libraries.",
      workTitle: "Features I own, database to interface",
      skills: [
        { title: "Frontend", icon: "react", items: ["TypeScript", "React", "Next.js", "Flutter", "Design systems", "Component libraries", "i18n", "Rendering performance"] },
        { title: "Backend", icon: "nodedotjs", items: ["Node.js", "NestJS", "Fastify", "Python", "REST API design", "GraphQL", "Webhooks", "Event-driven architecture"] },
        { title: "Data", icon: "postgresql", items: ["PostgreSQL", "Relational modeling", "Migrations", "Query optimization", "Redis", "ETL pipelines"] },
        { title: "Cloud & DevOps", icon: "docker", items: ["AWS Lambda", "SQS", "S3", "RDS", "Fargate", "Docker", "CI/CD"] },
        { title: "AI engineering", icon: "claude", items: ["Claude Code", "Claude Design", "Codex CLI", "Agentic workflows", "AWS Bedrock", "AgentCore"] },
        { title: "Practices", icon: "git-branch", iconSet: "ui", items: ["System design", "Automated testing", "Code review", "Documentation", "Mentoring", "Feature ownership"] },
      ],
    },
  },
  stats: [
    { value: "200k+", label: "Sessions delivered" },
    { value: "85k+", label: "Clients reached" },
    { value: "6+", label: "Years in production" },
    { value: "4–8", label: "Engineers led" },
  ],
  work: [
    {
      id: "keel-mind",
      title: "Keel Mind",
      role: "Feature Architect",
      period: "2022 — now",
      be: "A regulated mental-health platform: session domain modeling, API surface for web and mobile, and the reporting queries behind it.",
      fs: "A regulated mental-health platform: session domain, API surface, and the React and Flutter product surfaces on top of it.",
      metrics: ["200k+ sessions", "85k+ clients"],
      stack: ["NestJS", "PostgreSQL", "AWS", "React", "Flutter"],
    },
    {
      id: "notifications",
      title: "Event pipeline & notifications",
      role: "Design & delivery",
      period: "2023 — 2025",
      be: "Recording, transcription and post-session analysis moved off the request path with Lambda, SQS and S3 — plus the notification fan-out that rides on it.",
      fs: "Async processing for recording and transcription, with the in-product notification centre and delivery states that surface it to users.",
      metrics: ["Async by default", "Retry + idempotency"],
      stack: ["AWS Lambda", "SQS", "S3", "Elasticsearch"],
    },
    {
      id: "agent-tooling",
      title: "Agent tooling for the team",
      role: "Internal platform",
      period: "2024 — now",
      be: "Internal tooling over agent CLIs: an agent-driven first pass on pull requests, versioned convention files, reusable skills and machine-executable specs.",
      fs: "Internal tooling over agent CLIs, plus prototyping product interfaces with Claude Design before implementation.",
      metrics: ["Automated PR first pass", "Token budgets tuned"],
      stack: ["Claude Code", "Codex CLI", "Bedrock", "AgentCore"],
    },
    {
      id: "compras",
      title: "Compras Compartidas",
      role: "Senior Software Developer",
      period: "2020 — 2022",
      be: "The public REST API used by 50 to 200 partner stores a month — data contracts, PostgreSQL model, and the operational tooling around it.",
      fs: "Customer and store-facing web apps in React and Next.js, mobile in Flutter, over the public partner API I owned.",
      metrics: ["50–200 partner stores", "Funnel instrumented"],
      stack: ["Node.js", "Python", "PostgreSQL", "React", "Next.js"],
    },
  ],
  timeline: [
    {
      company: "Keel Mind, Canada (remote)",
      role: "Feature Architect",
      period: "March 2024 — present",
      location: "Remote",
      current: true,
      bullets: [
        "Lead technical design and delivery across backend, web, mobile and QA teams of four to eight engineers.",
        "Own PostgreSQL modeling for core domains: schema design, migrations, indexing and query tuning.",
        "Partner with Product to define scope, evaluate tradeoffs and sequence delivery.",
      ],
    },
    {
      company: "Keel Mind, Canada (remote)",
      role: "Senior Software Engineer",
      period: "June 2022 — March 2024",
      location: "Remote",
      bullets: [
        "Designed REST and GraphQL APIs for web and mobile clients across first responder, Indigenous, academic and education care programs.",
        "Built payment, calendar and distributed scheduling integrations with retries and idempotency.",
      ],
    },
    {
      company: "Compras Compartidas",
      role: "Senior Software Developer",
      period: "September 2020 — June 2022",
      location: "Bogotá",
      bullets: ["Owned the public REST API used by 50 to 200 partner stores each month, including its data contracts and PostgreSQL model."],
    },
    {
      company: "Meniu",
      role: "Full Stack Developer",
      period: "June 2019 — October 2020",
      location: "Bogotá",
      last: true,
      bullets: ["Shipped the platform used daily by 200+ restaurants, where partners ran 10% to 40% of their daily sales through the product."],
    },
  ],
  education: [
    { school: "Universidad de los Andes", degree: "BSc Systems and Computing Engineering", period: "2015 — 2019" },
    { school: "Universidad de los Andes", degree: "BSc Industrial Engineering", period: "2014 — 2019" },
  ],
};
